### ISSUE TITLE
I am wondering when exactly will the model and data be released?

### ISSUE THREAD

**Issue by Penny1012** [allenai/specter#1]
I am wondering when exactly will the model and data be released?

**Comment by utkuumur** [comment]
I am also waiting for this. But at the mean time you can slightly modify Sentence-Bert to come up with something closer. You can select CLS token instead of MEAN and modify readers and converters to 2 sentence format. Then start with scibert instead of defaults. It should perform similarly to this.

**Comment by armancohan** [comment]
Thanks for your interest. We expect to release the model within the next two weeks. 
Re Sentence-Bert: note that this is one of the baselines in our paper and we didn't have much success with it on document level tasks.

**Comment by utkuumur** [comment]
Thank you for your answer. I may be wrong but this is what I understood (Please correct me If I am wrong). Sentence-bert can also training embeddings from Transformers with only polling layer using triplets so isn't this equivalent to your training procedure? Only difference is Sentence-Bert comes with single sentence option which could be modified if you append the [sep] token.

I am working on a similar project,  I tried to summarize the long text into multiple sentences with 510 tokens and use it as as a single sentence without sep tokens. This works better  than using title or abstract alone in my case (double mAP score)  but  I never tried to combine title and abstract. Until now I trained with siamise network which I labeled cited documents 1 and randomly selected negatives as 0 which works bad with cosine similarity. After seeing your work I am using triplets with L2 distance. (which is more efficient)  I will get the results in a day. In my case there are 2m documents and best model achieves 0.06 mAP with cosine similarity. I will also try to combine title and abstract if I can manage.

**Comment by sergeyf** [comment]
Model and data are now released, so I'm closing this issue!
