### ISSUE TITLE
Streaming data for inferrence

### ISSUE THREAD

**Issue by ckald** [allenai/specter#11]
Hi! I'm trying to embed some 100M papers using SPECTER. However, there's some kind of a memory leak that makes the whole process extremely inefficient. I see that AllenNLP models support JSONL input format. 

What is the simplest way to replace the `ids` and `metadata` args with a single JSONL file or stdin?

**Comment by armancohan** [comment]
For prediction, the code already should support using JSONL format in streaming way.
See line [98](https://github.com/allenai/specter/blob/541fc2bf8b95118665082a335737508b3ce2c9b8/specter/predict_command.py#L88) in predict command.
And allennlp's [_get_json_data](https://github.com/allenai/allennlp/blob/052353ed62e3a54fd7b39a660e65fc5dd2f91c7d/allennlp/commands/predict.py#L176) command.
Our code currently reads the data twice. First it counts the number of lines in the input at [this line](https://github.com/allenai/specter/blob/541fc2bf8b95118665082a335737508b3ce2c9b8/specter/predict_command.py#L85). If you want to make if fully streamable remove the line and remove `total_size` from `tqdm` at lines [92](https://github.com/allenai/specter/blob/master/specter/predict_command.py#L92) and [97](https://github.com/allenai/specter/blob/master/specter/predict_command.py#L97) accordingly.

**Comment by armancohan** [comment]
Closing this for now. Feel free to open if you still have issues.
