### ISSUE TITLE
Label namespace warning

### ISSUE THREAD

**Issue by DWFlanagan** [allenai/specter#12]
When I run the sample code in the readme.md

```ruby
python scripts/embed.py \
--ids data/sample.ids --metadata data/sample-metadata.json \
--model ./model.tar.gz \
--output-file output.jsonl \
--vocab-dir data/vocab/ \
--batch-size 16 \
--cuda-device -1
```

I get a warning

```WARNING:allennlp.data.fields.label_field:Your label namespace was 'year'. We recommend you use a namespace ending with 'labels' or 'tags', so we don't add UNK and PAD tokens by default to your vocabulary.  See documentation for `non_padded_namespaces` parameter in Vocabulary.```

I still seem to generate meaningful embeddings, though. It's consistent across Windows 10 and OS X 10.15.6.

Thanks!

**Comment by armancohan** [comment]
You can safely ignore this warning. `year` is not used in the pretrained model.

**Comment by DWFlanagan** [comment]
Great, thanks.
