### ISSUE TITLE
How to set num_train_instances when using your pickled training data

### ISSUE THREAD

**Issue by lulujianjie** [allenai/specter#14]
Hi~, I am trying to training from scratch using the pickled data in #2. 

But the training process is stuck at  15143it with batchsize 32. I guess that I used the wrong param of num_train_instances (680000)

The error shows as following:
./scripts/run-exp-simple.sh: line 152: 18438 Killed                  python -m allennlp.run train $config_file --include-package specter -s $serialization_dir

**Comment by armancohan** [comment]
you may change this line: https://github.com/allenai/specter/blob/541fc2bf8b95118665082a335737508b3ce2c9b8/scripts/run-exp-simple.sh#L36

**Comment by armancohan** [comment]
Closing this for now. Feel free to re-open if you still have issues.

**Comment by ringkasannet** [comment]
Hi can i clarify that if we are to use the pickled training data in #2 , we dont need to set the --num-train-instances in the script because it already reflects the correct number of training instances which is 680000?

**Comment by shruti-singh** [comment]
> Hello,
In case someone else comes here looking for the same, the count of instances in the pickled training data in #2 is as follows:
train instances = 684100
val instances = 145375
