### ISSUE TITLE
Any plans to make the model available on the Transformers library?

### ISSUE THREAD

**Issue by rodrigonogueira4** [allenai/specter#17]
It would certainly increase its visibility :)

**Comment by armancohan** [comment]
Thanks for the interest! I agree this would make things more convenient. 
Unfortunately, in the short term we don't have bandwidth for integrating Specter into HF Transformers. But that could change in next couple of months. In the meantime we welcome any PRs regarding this.

**Comment by rodrigonogueira4** [comment]
Great, thanks for clarifying!

**Comment by armancohan** [comment]
This should be addressed now https://github.com/allenai/specter/pull/21

**Comment by rodrigonogueira4** [comment]
@armancohan, this is great, thanks!
