### ISSUE TITLE
query regarding information retrieval using text query

### ISSUE THREAD

**Issue by MukundVarmaT** [allenai/specter#18]
Hi! Thanks for sharing your amazing work. I had a query. 
I wanted to perform a similarity match between a query sentence and a larger text (title and abstract from arxiv papers). I created embeddings for the database. However, I was unsure about how I can create a similar embedding for the query text. I tried by keeping the query as the title and the abstract empty but the results were not good. Although i did notice this on the paper:

> We observe that removing the abstract from the textual input and relying only on the title results in a substantial decrease in performance

Do you have any suggestions as to what I can try out to improve? Thanks :)

PS: the embeddings for the papers themselves are pretty good as I tried finding the closest ones for a couple of samples and they all seem to be very consistent

**Comment by armancohan** [comment]
What you did (treating the query as a document and encoding it using SPECTER, then using similarity search) sounds reasonable. However SPECTER was not really designed or tested for IR tasks, so I wouldn't be surprised if it doesn't work very well for IR out of the box. 
That said, you could do some fine-tuning on a ranking dataset to improve it for IR tasks. Alternatively one could use SPECTER as a complementary method to the initial ranker (e.g., for Pseudo Relevance Feedback or finding additional similar documents to those ranked high by the ranker).
