### ISSUE TITLE
Training data and code to reproduce model training

### ISSUE THREAD

**Issue by urmeya** [allenai/specter#2]
Can you please release the training data and code to reproduce model training?
What is the expected timeline?

**Comment by armancohan** [comment]
We've already released the pretrained model weights and instructions on how to use it (please see the README.md)  

But if you are interested in training the model from scratch here are some instructions. 

```./scripts/run-exp-simple.sh -c experiment_configs/simple.jsonnet \
-s [output-dir] --num-epochs [num-epochs] --batch-size [batch-size] \
--train-path [path-to-train.pkl] --dev-path [path-to-dev.pkl] \
--cuda-device 0 
```
We will be releasing some instructions on using the model on custom data in the future, but in the meantime if you want to use our pickled training data you can download it from here (the files are relatively large):
train: [link](https://ai2-s2-research-public.s3-us-west-2.amazonaws.com/specter/training-data/train.pkl) [15.6G]
validation: [link](https://ai2-s2-research-public.s3-us-west-2.amazonaws.com/specter/training-data/val.pkl) [3.5G]

**Comment by bigheiniu** [comment]
@armancohan Can you provide the dataset including data.json, metadata.json? Just like what you discussed in the readme file.
