### ISSUE TITLE
Model name 'data/scibert_scivocab_uncased/vocab.txt' was not found in model name list

### ISSUE THREAD

**Issue by hintonian** [allenai/specter#25]
Hi, I think I'm doing something really dumb but I don't know how to fix it.

I'm trying to run `create_training_files.py` as per the instructions, but I'm getting the error in the title. This file does not exist in the specter repository. Am I supposed to download it from somewhere else?

**Comment by armancohan** [comment]
Could you try downloading the supporting files first?
Instructions in readme: https://github.com/allenai/specter#download

**Comment by hintonian** [comment]
Ah right, sorry I missed the unzip step when I was following the instructions
