### ISSUE TITLE
Training Data Set for Spectre

### ISSUE THREAD

**Issue by ringkasannet** [allenai/specter#29]
Hi all, great job developing such robust model. 

I am trying to replicate your model for assignment in my uni.  I read in your paper that you are releasing your training dataset however I am still unable to find it anywhere. I also understand that Scidocs is just for evaluation purposes. If you are unable to release the dataset, can you at least share the method you use to determine the dataset you are using.

Cheers

**Comment by armancohan** [comment]
Hi, thanks for your interest. 
Please see this issue for downloading the training data: https://github.com/allenai/specter/issues/2
The instructions to re-train the model are also provided in the Readme.

**Comment by ringkasannet** [comment]
Hi Cohan, thank so much for this! cheers

**Comment by ringkasannet** [comment]
Hi, can i clarify what is the correct number for the --num-train-instances if we are to use this pickled file? Should we use the default value of 680000?

**Comment by armancohan** [comment]
Yes, this is the correct number of instances.

**Comment by armancohan** [comment]
I'll close this issue for now. Feel free to re-open if you still have issues/questions.
