### ISSUE TITLE
Help required for training data preparation

### ISSUE THREAD

**Issue by victor714** [allenai/specter#3]
I want to train SPECTER on my data. 

I checked following script for generating pickled training files: `specter/data_utils/create_training_files.py`

As per my understanding it requires following inputs:
- data.json [(line 489)](https://github.com/allenai/specter/blob/f897c99d4a68416a1719b7d5795ff1261afc3aa0/specter/data_utils/create_training_files.py#L489)
- metadata.json
- train.csv, val.csv, test.csv

Please help me with the schema required for data.json and metadata.json files, columns in train.csv, val.csv, test.csv and instructions about any other required files or pre-processing steps.

**Comment by armancohan** [comment]
We plan to release a more easier interface for training the model in the future.

In the meanwhile, you can format your data according to the following:
First you need to create a `data.json` file (a nested dict) with the following structure:  
```ruby
{"docid1" : {  "docid11": {"count": 1}, 
               "docid12": {"count": 5},
               "docid13": {"count": 1}, ....
            }
"docid2":   {  "docid21": {"count": 1}, ....
....}
```

Where `docids` are ids of documents in your data and `count` is a measure of importance of the relationship between two documents. In our dataset we used citations as indicator of relationsship where `count=5` means direct citation while `count=1` refers to a citation of a citation.  

`metadata.json` is a file containing mapping of document ids with actual textual fields (`title`, `abstract`, etc).   
 
`train.csv`, `val.csv`, `test.csv` include document ids in each of the training, validation and test sets. These files include one document id per line.
  
The `create_training_files.py` script processes this structure with a triplet sampler that selects both easy and hard negatives (as described in the paper) according the `count` value in the above structure. For example papers with `count=5` are considered positive candidates, papers with `count=1` considered hard negatives and other papers that are not cited are easy negatives. You can control the number of hard negatives by setting `--ratio_hard_negatives` argument in the script.

**Comment by armancohan** [comment]
The detailed instructions about training are in the readme. Closing this issue.
Feel free to reopen if you have issues.

**Comment by victor714** [comment]
I have a query regarding training data preparation. 
README file says that while preparing `data.json`, `count=5` means direct citation while `count=1` refers to a citation of a citation.
For hard negatives, we need citation of a citation which is not cited in the original document. So is it taken care of by `create_training_files.py` script?

To make my query more clear, is the following `data.json` file correct ? `"docid13"` is cited in `"docid1"` and also in `"docid12"`

```
{"docid1" : {  "docid11": {"count": 1}, 
               "docid12": {"count": 5},
               "docid13": {"count": 5},
               "docid13": {"count": 1}, ....
            }
"docid2":   {  "docid21": {"count": 1}, ....
....}
```

**Comment by armancohan** [comment]
No, you shouldn't put both counts for a single paper pair. 
We exclude papers that are cited by the original paper from hard negative candidates. 
So in your example above, `docid13` should only have a `"count": 5". Removing the row after it makes it correct. 
If `docid13` was not cited by `docid` then `"count":1" was correct.
