### ISSUE TITLE
Positive paper sampling

### ISSUE THREAD

**Issue by malteos** [allenai/specter#36]
In your paper it says:

> The positive paper is a paper that is not cited by the query paper.

Does this mean that citations are considered as unidirectional such that a paper citing the query could be a negative sample for the query?

Thanks!

**Comment by armancohan** [comment]
Yes the citations are considered unidirectional. But to clarify, as we say in the paper:

> The positive paper is a paper that the query paper cites, and the negative paper is a paper that is not cited by the query paper

While unlikely the scenario that you describe is possible through random negative sampling.
